version: '3'

services:
  anythingllm:
    image: ghcr.io/mintplex-labs/anything-llm:latest
    container_name: anythingllm
    ports:
      - "3000:3000"  # REST API (kann auch bleiben)
      - "3001:3001"  # GUI
    volumes:
      - anythingllm-data:/app/server/storage
      - ./skills:/app/skills  # Mount für Custom Skills
    environment:
      - NODE_ENV=production
      - STORAGE_DIR=/app/server/storage
      - CUSTOM_SKILLS_DIR=/app/skills  # <<< wichtig für Agent Skills
    restart: unless-stopped

volumes:
  anythingllm-data:
